spring:
  application:
    name: ms-security

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: #username de la DB
    password: #password de la DB
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: #crear secret key Seguro Para HS512
  expiration:
    access: 600000
    refresh: 604800000
